loja/config/routes.rb
Loja::Application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :sectors
  resources :operators
  resources :categories
  resources :products

  resources :store, only:[:index, :show]
  resources :admin, only:[:index]
  
  root 'store#index'
end

loja/app/models/product.rb
class Product < ActiveRecord::Base
    has_and_belongs_to_many :categories
	validates :title, :description, :image_url, presence: true
	validates :price, numericality: { greater_than_or_equal_to: 0.01 }
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png|jpeg)\Z}i,
		message: 'must be a URL for GIF, JPG or PNG image.'
	}
	def self.latest
		Product.order(:updated_at).last
	end

	def self.order_by_name
		Product.order(:name)
	end
end

loja/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authorize, only:[:show]
  before_action :set_product, :set_category, only:[:show, :edit, :update, :destroy]
  
  def index
    @products = Product.all
  end

  def show
    @product = Product.includes(:categories).find(params[:id])
  end

  def new
    @product = Product.new
    @categories = Category.all.map { |c| [ c.title, c.id ] }
  end

  def edit
    @categories = Category.all.map{ |c| c.title }
  end

  def create
    @product = Product.new(product_params)
    @product.categories_id = params[:categories_id]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product.categories_id = params[:categories_id]
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category_id)
    end

    def category_params
      params.require(:category).permit(:title, :product_id)
    end
end

loja/app/helpers/products_helper.rb
module ProductsHelper
end

loja/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

	<% if @product.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</div>
	<div class="field"><br>
		<%= f.label :description %><br>
		<%= f.text_area :description, rows: 6 %><br>
	</div>
	<div class="field"><br>
		<%= f.label :image_url %><br>
		<%= f.text_field :image_url %><br>
	</div>
	<div class="field"><br>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</div>
	<div class="checkbox"><br>
		<%= f.collection_check_boxes :categories_id, Category.all, :id, :title %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

loja/app/views/products/create.html.slim
h1 Products#create
p Find me in app/views/products/create.html.slim

loja/app/views/products/destroy.html.slim
h1 Products#destroy
p Find me in app/views/products/destroy.html.slim

loja/app/views/products/edit.html.slim
h1 Edit Product

= render 'form'
br
br

.redirect_button
	=link_to 'Back', products_path

loja/app/views/products/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1 class="centered_item">Listing Products</h1>
<div class="list_actions centered_item">
  <h2><%= link_to '| New Product |', new_product_path %></h2>
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th class="centered_th">Categories</th>
  </tr>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td><%= product.title.titleize %></td>
      <td><%= number_to_currency(product.price) %></td>
      <td><%= truncate(product.categories.map { |c| c.title.titleize }.join(', '), length: 100) %></td>
      <td class="list_actions">
        <%= link_to 'Show', product %> |
        <%= link_to 'Edit', edit_product_path(product) %> |
        <%= link_to 'Delete', product, method: :delete,
                data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

loja/app/views/products/index.html.slim
h1 Products#index
p Find me in app/views/products/index.html.slim

loja/app/views/products/new.html.slim
h1 New Product

= render 'form'
br
br

.redirect_button
	= link_to 'Back', products_path

loja/app/views/products/show.html.erb
<div id="show">
	<p>
		<strong>ID:</strong>
		<%= @product.id %>
	</p>

	<p>
		<strong>Title:</strong>
		<%= @product.title.titleize %>
	</p>

	<p>
		<strong>Description:</strong>
		<%= @product.description %>
	</p>

	<p>
		<%= image_tag(@product.image_url, class: 'list_image') %>
	</p>

	<p>
		<strong>Price:</strong>
		<%= number_to_currency(@product.price) %>
	</p>

	<p>
		<strong>Categories:</strong>
		<% @product.categories.each do |category| %>
			<span class='list_actions'><%= link_to category.title, category_path %></span>&nbsp;
		<% end %>		
	</p>

	<% if session[:operator_id] %>
		<p>
			<strong>Created at:</strong>
			<%= @product.created_at %>
		</p>

		<p>
			<strong>Updated at:</strong>
			<%= @product.updated_at %>
		</p>

		<div class="redirect_button"><br>
			<%= link_to 'Edit', edit_product_path(@product) %> |
			<%= link_to 'Back', products_path %>
		</div>

	<% else %>
		<div class="redirect_button"><br>
			<%= link_to 'Back', root_url %>
		</div>
	<% end %>
</div>

loja/app/views/products/show.html.slim
h1 Products#show
p Find me in app/views/products/show.html.slim

loja/app/views/products/update.html.slim
h1 Products#update
p Find me in app/views/products/update.html.slim