loja/config/routes.rb
Loja::Application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :sectors
  resources :operators
  resources :categories
  resources :products

  resources :store, only:[:index, :show]
  resources :admin, only:[:index]
  
  root 'store#index'
end

loja/app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :products
    validates :title, presence: true
    validates :title, uniqueness: true
    
    def self.latest
        Category.order(:updated_at).last
    end
    
end

loja/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authorize, only:[:show]
  
  def index
    @categories = Category.all
  end

  def show
    set_category
    @products = Product.all
  end

  def new
    @category = Category.new
    @products = Product.all
  end

  def edit
    set_category
    @products = Product.all.map { |p| p.title }
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :index, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :index, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_category
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :product_id)
  end

  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price, :category_id)
  end
end

loja/app/helpers/categories_helper.rb
module CategoriesHelper
end

loja/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

	<% if @category.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</div>
  <div class="checkbox">
    <p>Products</p>
    <%= f.collection_check_boxes :products_id, Product.all, :id, :title %>
  </div>
	<div class="actions"><br>
		<%= f.submit %>
	</div>

<% end %>

loja/app/views/categories/edit.html.slim
h1 Edit Category

= render 'form'
br
br

.redirect_button
	= link_to 'Back', categories_path

loja/app/views/categories/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1 class="centered_item">Listing Categories</h1>

<div class="list_actions centered_item">
  <h2><%= link_to '| New Category |', new_category_path %></h2>
</div>

<table class="item_list">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th class="centered_th">Products</th>
    <th>Created at</th>
    <th>Updated at</th>
  </tr>
  <% @categories.each do |category| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td><%= category.id %></td>
      <td><%= category.title.titleize %></td>
      <td><%= truncate(category.products.map { |c| c.title.titleize }.join(', '), length: 40) %></td>
      <td><%= category.created_at %></td>
      <td><%= category.updated_at %></td>
      <td class="list_actions">
        <%= link_to 'Show', category %> |
        <%= link_to 'Edit', edit_category_path(category) %> |
        <%= link_to 'Delete', category_path(category), class: 'cpy-delete-category', method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

loja/app/views/categories/new.html.slim
h1 New Category

=render 'form'
br
br

.redirect_button
	=link_to 'Back', categories_path

loja/app/views/categories/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1 class="centered_item">Listing Products</h1>
<h3 class="centered_item">Showing only: <%= @category.title.titleize %></h3>

<table>
  <% @category.products.each do |product| %>
    <div id="product_box">
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= link_to image_tag(product.image_url, class: 'list_image'), product %>
        </td>
        <td class="list_description">
          <dl>
           <dt><strong><span class='list_actions'><%= link_to product.title.titleize, product %></span></strong></dt><br>
            <dt><%= number_to_currency(product.price) %></dt><br/><br/>
          </dl>
        </td>
      </tr>
    </div>
  <% end %>
</table>
<br>