loja/config/routes.rb
Loja::Application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :sectors
  resources :operators
  resources :categories
  resources :products

  resources :store, only:[:index, :show]
  resources :admin, only:[:index]
  
  root 'store#index'
end

loja/app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html ng-app='IlsApp'>
  <head>
    <title><%= @page_title || "Barney Shop" %></title>
    <%= stylesheet_link_tag("application", :media => "all") %>
    <%= javascript_include_tag("application") %>
    <%= csrf_meta_tags %>
  </head>

	<body class="<%= controller.controller_name %>">
		<div class="banner">
			<img src="http://i.imgur.com/1ikiqUj.jpg?1"/>
		</div>

		<div class ="nav">
			<div class="row, clearfix">
				<div class="col-sm-3">
					<ul>
						<li class="clearfix"><%= link_to("Home", root_path) %></li>
						<% if session[:operator_id] %>
							<li class="clearfix"><%= link_to("Logout", logout_path,
													 method: :delete) %></li>
							<span>Logged as: "<%= Operator.find(session[:operator_id]).name %>"</span>
						<% else %>
							<li class="clearfix cpy-login-btn"><%= link_to("Login", login_url) %></li>
						<% end %>
					</ul>

					<% if session[:operator_id] %>
						<div id="js-menu">
							<h2>Admin Menu</h2>
							<img id="js-menu_icon" src="http://i.imgur.com/4Kav6g5.png?1">
						</div>
						<div id="js-menu_expanded">
							<ul>
								<li class="clearfix"><%= link_to("Products", products_path) %></li>
								<li class="clearfix"><%= link_to("Categories", categories_path) %></li>
								<li class="clearfix"><%= link_to("Sectors", sectors_path) %></li>
								<li class="clearfix"><%= link_to("Operators", operators_path) %></li>
							</ul>
						</div>
					<% end %>

				</div>
			</div>
		</div>
		<div id="js-categories">
			<h2>Categories</h2>
			<img id="js-categories_icon" src="http://i.imgur.com/4Kav6g5.png?1">
		</div>
		<div id="js-categories_expanded" class="cpy-categories_expanded">
			<ul>
				<% Category.all.each do |category| %>
					<li><%= link_to category.title.titleize, category %></li>
				<% end %>
			</ul>
		</div>
		<div class="container">
			<div class="row, clearfix">
				<div class="col-sm-9">
					<%= yield %>
				</div>
			</div>
		</div>
	
		<footer>
			<p>Copyright © 2015 BarneyShop All right reserved</p>
		</footer>
  	</div>
  </body>
</html>

loja/app/views/layouts/application.html.slim
| <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
html ng-app='IlsApp'
  head
    title
      | Projeto loja
    = stylesheet_link_tag("application", :media => "all")
    = javascript_include_tag("application")
    = csrf_meta_tags

body
  = yield