loja/config/routes.rb
Loja::Application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :sectors
  resources :operators
  resources :categories
  resources :products

  resources :store, only:[:index, :show]
  resources :admin, only:[:index]
  
  root 'store#index'
end

loja/app/models/operator.rb
class Operator < ActiveRecord::Base
  belongs_to :sector

  #before_create :create_activation_digest
  before_save { email.downcase! }

  validates :name, :sector, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  #def Operator.digest(string)
  #  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                BCrypt::Engine.cost
  #  BCrypt::Password.create(string, cost: cost)
  #end

  # Returns a random token.
  #def Operator.new_token
  #  SecureRandom.urlsafe_base64
  #end

  #def remember
  #  self.remember_token = Operator.new_token
  #  update_attribute(:remember_digest, Operator.digest(remember_token))
  #end

  #def authenticated?(remember_token)
  #  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  #end

  #def create_activation_digest
  #  self.activation_token = Operator.new_token
  #  self.create_activation_digest = Operator.digest(activation_token)
  #end

  private
    def downcase_email
      self.email = email.downcase
    end
end

loja/app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  def index
    @operators = Operator.all
    @sectors = Sector.all
  end

  def show
    set_operator
  end

  def new
    @operator = Operator.new
    @sectors = Sector.all
  end

  def edit
    set_operator
    authorize_full_access
  end

  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render :index, status: :created, location: @operator }
      else
        format.html { render :new }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_operator

    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { render :index, status: :ok, location: @operator }
      else
        format.html { render :edit }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in.sector.id == 7 && logged_in.sector.title == 'Admin'
      set_operator
      @operator.destroy

      respond_to do |format|
        format.html { redirect_to operators_url, notice: 'Operator was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      redirect_to admin_index_url, alert: "Only operators who belong in the 'Admin' sector have access to this."
    end
  end

  private
  def set_operator
    @operator = Operator.find(params[:id])
  end

  def operator_params
    params.require(:operator).permit(:id, :name, :email, :password, :password_confirmation, :sector_id)
  end

  def sector_params
    params.require(:sector).permit(:id, :title, :operators_id)
  end
end

loja/app/helpers/operators_helper.rb
module OperatorsHelper
end

loja/app/views/operators/_form.html.erb
<%= form_for(@operator) do |f| %>

	<% if @operator.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% @operator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
	</div>

  <div class="field"><br>
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
  </div>

  <div class="field"><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
  </div>

  <div class="field"><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
  </div>

  <div class="select"><br>
    <% if logged_in.sector.id == 7 && logged_in.sector.title == 'Admin' %>
      <%= f.collection_select(:sector_id, Sector.all, :id, :title, :include_blank => "Choose Sector") %>
    <% else %>
      <%= f.collection_select(:sector_id, Sector.where.not(title: 'Admin'), :id, :title, :include_blank => "Choose Sector") %>
    <% end %>
  </div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

loja/app/views/operators/edit.html.slim
h1 Edit Operator

= render 'form'
br
br

.redirect_button
	= link_to 'Back', operators_path

loja/app/views/operators/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1 class="centered_item">Listing Operators</h1>

<div class="list_actions centered_item">
  <h2><%= link_to '| New Operator |', new_operator_path %></h2>
</div>

<table class="item_list">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Sector</th>
    <th>Created at</th>
    <th>Updated at</th>
  </tr>
  <% @operators.each do |operator| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td><%= operator.id %></td>
      <td><%= operator.name.titleize %></td>
      <td><%= operator.email %></td>
      <td><%= operator.sector.title.titleize %></td>
      <td><%= operator.created_at %></td>
      <td><%= operator.updated_at %></td>
      <td class="list_actions">
        <%= link_to 'Show', operator %> |
        <%= link_to 'Edit', edit_operator_path(operator) %> |
        <%= link_to 'Delete', operator_path(operator), method: :delete,
                data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

loja/app/views/operators/index.html.slim
h1 Operators#index
p Find me in app/views/operators/index.html.slim

loja/app/views/operators/new.html.slim
h1 New Operator

= render 'form'
br
br

.redirect_button
	=link_to 'Back', operators_path

loja/app/views/operators/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<div id="show">
	<p>
		<strong>ID:</strong>
		<%= @operator.id %>
	</p>

	<p>
	  <strong>Name:</strong>
	  <%= @operator.name.titleize %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @operator.email %>
	</p>

	<p>
		<strong>Sector:</strong>
		<% if @operator.sector %>
			<span class='list_actions'><%= link_to @operator.sector.title.titleize, @operator.sector %></span>&nbsp;
		<% end %>
	</p>

	<p>
		<strong>Created at:</strong>
		<%= @operator.created_at %>
	</p>

	<p>
		<strong>Updated at:</strong>
		<%= @operator.updated_at %>
	</p>


	<div class="redirect_button"><br>
	  <%= link_to 'Edit', edit_operator_path(@operator) %> |
	  <%= link_to 'Back', operators_path %>
	</div>
</div>